POST http://localhost:8080/secured/todos
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNzZyIsImVtYWlsIjoic3NnQGdvLmNvbSIsImV4cCI6MTcwOTA1MjI1Nn0.C1wXq4KvZoLND4nY82J-_1hixAaO52OoR0x9AoDIMHg

{
  "title": "New Todo",
  "status": "pending"
}
